import Head from 'next/head'
import { Inter } from '@next/font/google'
import { Navbar,SideBar, Body } from '@/containers'
import { createContext,useState } from 'react'




export const AppContext = createContext({
  bgType: '',
  setBgType: (bgType: string) => {},
  response: false,
  setResponse: (response: boolean) => {
    console.log(response)
  },
  bgColor: '',
  setBgColor: (bgColor: string) => {},
  fontSize: '',
  setFontSize: (fontSize: string) => {},
  cardColor: '',
  setCardColor: (cardColor: string) => {},

})

const inter = Inter({ subsets: ['latin'] })

export default function Home() {


  const [bgType, setBgType] = useState('')
  const [response, setResponse] = useState(false)
  const [bgColor, setBgColor] = useState('')
  const [fontSize, setFontSize] = useState('')
  const [cardColor, setCardColor] = useState('')

  return (
    <AppContext.Provider value={{
      bgType,setBgType,
      response,setResponse,
      bgColor,setBgColor,
      fontSize,setFontSize,
      cardColor,setCardColor
    }}>
      <Head>
        <title>Aperturs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className= 'relative h-screen'>
        <Navbar />
        <SideBar />
        <div className='absolute min-h-screen min-w-full flex justify-center top-0
         left-0 items-center '>  
        <Body />
        </div>  
      </section>    
     </AppContext.Provider>     
    )
}


