import Head from 'next/head'
import { Inter } from '@next/font/google'
import { Navbar,BottomBar } from '@/containers'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Aperturs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className='relative h-[100vh]'>
      <Navbar />
      <BottomBar />
      </section>    
    </>
  )
}


